const activationInfo={sigmoid:{description:'Wygładza wynik do zakresu od 0 do 1. Dobry wybór dla klasyfikacji.',range:'0 → 1',use:'klasyfikacja',path:'M0 128 C42 128 84 126 120 113 C160 96 184 64 210 49 C242 32 270 31 300 31',output:'0.50'},relu:{description:'Przepuszcza wartości dodatnie, a ujemne zamienia na zero. Szybka i popularna.',range:'0 → ∞',use:'warstwy ukryte',path:'M0 145 L145 145 L300 18',output:'0.00'},tanh:{description:'Zwraca wartości od -1 do 1 i centruje dane wokół zera.',range:'-1 → 1',use:'dane centrowane',path:'M0 145 C50 145 80 136 110 118 C150 94 170 66 200 47 C238 23 270 18 300 18',output:'0.00'},linear:{description:'Nie zmienia wartości. Przydatna, gdy neuron ma zwracać wynik ciągły.',range:'-∞ → ∞',use:'regresja',path:'M0 140 L300 28',output:'0.00'},leaky_relu:{description:'Jak ReLU, ale zachowuje małe wartości ujemne zamiast zerować je całkowicie.',range:'-∞ → ∞',use:'warstwy ukryte',path:'M0 156 L145 145 L300 18',output:'0.00'},step:{description:'Twarda funkcja progowa: zwraca 0 albo 1 zależnie od znaku wartości.',range:'0 lub 1',use:'prosty próg',path:'M0 145 L148 145 L148 22 L300 22',output:'0.00'}};
const name=document.querySelector('#activation-name'),desc=document.querySelector('#activation-description'),range=document.querySelector('#activation-range'),use=document.querySelector('#activation-use'),path=document.querySelector('#activation-path'),output=document.querySelector('#demo-output'),inputValue=document.querySelector('#demo-input'),slider=document.querySelector('#demo-slider');
let selectedActivation='sigmoid';
function activationValue(key,value){if(key==='sigmoid')return 1/(1+Math.exp(-value));if(key==='relu')return Math.max(0,value);if(key==='tanh')return Math.tanh(value);if(key==='linear')return value;if(key==='leaky_relu')return value>=0?value:0.01*value;return value>=0?1:0;}
function renderActivation(){const value=Number(slider.value),info=activationInfo[selectedActivation];name.textContent=selectedActivation;desc.textContent=info.description;range.textContent=info.range;use.textContent=info.use;inputValue.textContent=value.toFixed(1);output.textContent=activationValue(selectedActivation,value).toFixed(3);path.setAttribute('d',info.path);}
const activationButtons=[...document.querySelectorAll('[data-activation]')];
activationButtons.forEach(button=>button.addEventListener('click',()=>{activationButtons.forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});button.classList.add('active');button.setAttribute('aria-selected','true');selectedActivation=button.dataset.activation;renderActivation();}));
slider?.addEventListener('input',renderActivation);
renderActivation();
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const text=document.getElementById(button.dataset.copy).innerText;try{await navigator.clipboard.writeText(text);button.textContent='Skopiowano ✓';setTimeout(()=>button.textContent='Kopiuj',1500)}catch{button.textContent='Zaznacz kod'}}));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Otwórz menu':'Zamknij menu');nav.classList.toggle('is-open',!open)});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav.classList.remove('is-open')}));
const progress=document.querySelector('.scroll-progress span');
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`},{passive:true});
